### ISSUE TITLE
Is it possible to support Windows?

### ISSUE THREAD

**Issue by naikrovek** [rviscarra/webrtc-remote-screen#1]
I would like to see support for sharing a monitor from Windows, if possible.  Well, I know it's possible, I just don't know if it's possible using Go.

OBS can do what I want, but the latency is absolutely insane.  I'm looking for more of a realtime solution, so I can show a group of people something on my screen while I talk to them on the phone using only a web browser on the viewing side, AND provide a very low latency viewing experience.

Assume that a valid HTTPS certificate is used on the web server of the Windows machine that shares it's screen.

**Comment by rviscarra** [comment]
I tried it on Windows, it crashes because of [this](https://github.com/gen2brain/x264-go/issues/5). 
I'll see if I can debug a bit more and figure out what's going on.

**Comment by ezoonet** [comment]
it's cool

**Comment by naikrovek** [comment]
It's been a while - did you get anywhere?  I'm hoping so.

it's almost certainly not a huge performance hit (and it is definitely not a problem for me) if you use a native x264 dll for Windows and call it like this: https://github.com/golang/go/wiki/WindowsDLLs 

I don't know how much a native DLL and the x264 library differ in terms of API.

**Comment by rviscarra** [comment]
Hey @naikrovek, sorry it took a while to get back at you. 

Unfortunately the DLL won't work since the x264-go library includes the sources of the x264 library it uses. The good news is that I added support for VP8 a few weeks ago so the x264 issue is no longer a blocker.

I don't think I'll be able to try VP8 on Windows for a couple of weeks but let me know if you do! :smile:

**Comment by naikrovek** [comment]
Compilation on Windows is not trivial for me for some reason.  I can set up MinGW and MSYS fine but things just don't work.  I hate C so much because of things like this.

**Comment by naikrovek** [comment]
Got it built - it took a few hours.  

Does this only capture from an X server, or can it capture from Windows?

**Comment by naikrovek** [comment]
OK, I need to do more testing before I fire off comments to people I don't know.

It works on Windows with VP8.

![image](https://user-images.githubusercontent.com/284498/65625366-4c9b2a00-df91-11e9-9e19-b38d246ac5be.png)


Now, can you add HTTPS?  😃

**Comment by rviscarra** [comment]
> It works on Windows with VP8

That's great news!

> Now, can you add HTTPS?

I could add CLI flags to specify a cert. and a key but I don't see that being useful in general since you need to register a domain, generate a cert., expose a port if you're behind NAT, etc ...

If your use case is still the same I think [ngrok](https://ngrok.com/) or [localtunnel](https://localtunnel.github.io/www/) can work for you, just keep in mind that if your share your session with multiple peers each WebRTC connection will spawn its own screen fetch / encode routines since it isn't optimized for that use case. :grin:

**Comment by naikrovek** [comment]
HTTPS is useful for me since WebRTC requires a secure connection.  I'm using this software inside a corporate network and certs are not an issue.

Other available screen sharing applications here are either high latency or very low frame rate.

I'll see about adding HTTPS support since it doesn't fit the general use case.

Thank you for the help.
